from __future__ import annotations

import ipaddress
import json
import re
from pathlib import Path
from typing import Any

from ..common import atomic_write, run
from ..context import Ctx

HANDLED_TYPES = {
    "security_apply",
    "ufw_enable", "ufw_disable", "ufw_allow", "ufw_delete", "ufw_reload", "ufw_default", "ufw_rule", "ufw_apply_ports",
    "fail2ban_reload", "fail2ban_ban_ip", "fail2ban_unban_ip", "fail2ban_apply_panel_config",
    "firewall_block_ip", "firewall_unblock_ip",
}


def truthy(v: Any) -> bool:
    return str(v or "").strip().lower() in {"1", "true", "yes", "on", "ano"}


def int_setting(ctx: Ctx, key: str, default: int, lo: int, hi: int) -> int:
    try:
        n = int(str(ctx.setting(key, str(default))).strip())
    except Exception:
        n = default
    return max(lo, min(hi, n))


def f2b_time_value(value: Any, default: str = "3600") -> str:
    raw = str(value if value is not None else default).strip().lower()
    if raw == "-1":
        return "-1"
    # Fail2ban bere čisté sekundy i zkratky typu 10m, 24h, 7d, 1w.
    if re.match(r"^[1-9][0-9]*(?:s|m|h|d|w)?$", raw):
        return raw
    return default


def rate_setting(ctx: Ctx) -> str:
    raw = str(ctx.setting("security_nginx_rate", "10r/s")).strip().lower().replace(" ", "")
    if re.match(r"^[1-9][0-9]*(r/s|r/m)$", raw):
        return raw
    if raw.isdigit() and int(raw) > 0:
        return raw + "r/s"
    return "10r/s"


def ip_lines(text: Any) -> list[str]:
    out: list[str] = []
    for line in str(text or "").replace(",", "\n").splitlines():
        item = line.strip()
        if not item or item.startswith("#"):
            continue
        try:
            if "/" in item:
                ipaddress.ip_network(item, strict=False)
            else:
                ipaddress.ip_address(item)
            out.append(item)
        except Exception:
            continue
    return out


def ensure_security_files(ctx: Ctx | None = None) -> None:
    rate = "10r/s"
    burst = 30
    conn = 30
    enabled = False
    if ctx is not None:
        rate = rate_setting(ctx)
        burst = int_setting(ctx, "security_nginx_burst", 30, 1, 10000)
        conn = int_setting(ctx, "security_nginx_conn", 30, 1, 10000)
        enabled = truthy(ctx.setting("security_nginx_rate_enabled", "0"))

    Path("/etc/nginx/conf.d").mkdir(parents=True, exist_ok=True)
    Path("/etc/nginx/snippets").mkdir(parents=True, exist_ok=True)

    atomic_write("/etc/nginx/conf.d/oris-security-zones.conf", f"""# ORIS Security Center - global zones
# Generated by ORIS provisioner. Do not edit manually.
limit_req_zone $binary_remote_addr zone=oris_req:20m rate={rate};
limit_conn_zone $binary_remote_addr zone=oris_conn:20m;
""")

    if enabled:
        body = f"""# ORIS Security Center - vhost rate limits
limit_req zone=oris_req burst={burst} nodelay;
limit_conn oris_conn {conn};
"""
    else:
        body = "# ORIS Security Center - rate limit disabled\n"
    atomic_write("/etc/nginx/snippets/oris-rate-limit.conf", body)


def access_lines(ips: list[str], indent: str = "    ") -> str:
    if not ips:
        return ""
    return "\n".join(f"{indent}allow {ip};" for ip in ips) + f"\n{indent}deny all;\n"


def write_phpmyadmin_snippet(ctx: Ctx) -> None:
    Path("/etc/nginx/snippets").mkdir(parents=True, exist_ok=True)
    rate_line = ""
    if truthy(ctx.setting("security_phpmyadmin_rate_enabled", "1")):
        rate_line = "    include snippets/oris-rate-limit.conf;\n"
    allow = ""
    if truthy(ctx.setting("security_phpmyadmin_allowlist_enabled", "0")):
        allow = access_lines(ip_lines(ctx.setting("security_phpmyadmin_allowlist", "")), "    ")
    guard = rate_line + allow
    atomic_write("/etc/nginx/snippets/phpmyadmin.conf", f"""# ORIS phpMyAdmin snippet
# Generated by ORIS Security Center / installer.
location = /phpmyadmin {{
    return 301 /phpmyadmin/;
}}

location /phpmyadmin/ {{
{guard}    alias /usr/share/phpmyadmin/;
    index index.php index.html;
    try_files $uri $uri/ /phpmyadmin/index.php?$query_string;
}}

location ~ ^/phpmyadmin/(.+\\.php)$ {{
{guard}    alias /usr/share/phpmyadmin/$1;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME /usr/share/phpmyadmin/$1;
    fastcgi_param SCRIPT_NAME /phpmyadmin/$1;
    fastcgi_param DOCUMENT_ROOT /usr/share/phpmyadmin;
    fastcgi_pass unix:/run/php/php-fpm.sock;
}}

location ~* ^/phpmyadmin/(.+\\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt|svg|woff|woff2|ttf|map))$ {{
{allow}    alias /usr/share/phpmyadmin/$1;
    expires 7d;
    access_log off;
}}
""")


def write_fail2ban_filters() -> None:
    Path("/etc/fail2ban/filter.d").mkdir(parents=True, exist_ok=True)
    atomic_write("/etc/fail2ban/filter.d/oris-nginx-phpmyadmin.conf", r'''[Definition]
failregex = ^<HOST> - .* "(?:GET|POST|HEAD) /phpmyadmin(?:/|\s|\?).*" (?:401|403|404|429|444)
ignoreregex =
''')
    atomic_write("/etc/fail2ban/filter.d/oris-nginx-badbots.conf", r'''[Definition]
failregex = ^<HOST> - .* "(?:GET|POST|HEAD) .*(?:wp-login\.php|xmlrpc\.php|\.env|/vendor/|/\.git/).*" (?:400|401|403|404|444)
ignoreregex =
''')
    atomic_write("/etc/fail2ban/filter.d/oris-perm.conf", r'''[Definition]
failregex = ^.*ORIS-PERM-BAN <HOST>.*$
ignoreregex =
''')


def write_fail2ban_config(ctx: Ctx) -> None:
    Path("/etc/fail2ban/jail.d").mkdir(parents=True, exist_ok=True)
    Path("/var/log/nginx").mkdir(parents=True, exist_ok=True)
    for log in ("/var/log/nginx/access.log", "/var/log/nginx/error.log", "/var/log/fail2ban.log", "/var/log/oris-security.log"):
        Path(log).touch(exist_ok=True)
        try:
            Path(log).chmod(0o640)
        except Exception:
            pass
    write_fail2ban_filters()
    bantime = int_setting(ctx, "security_fail2ban_bantime", 3600, 60, 2592000)
    findtime = int_setting(ctx, "security_fail2ban_findtime", 600, 60, 86400)
    maxretry = int_setting(ctx, "security_fail2ban_maxretry", 5, 1, 1000)
    pma_enabled = "true" if truthy(ctx.setting("security_fail2ban_phpmyadmin_enabled", "1")) else "false"
    bots_enabled = "true" if truthy(ctx.setting("security_fail2ban_badbots_enabled", "1")) else "false"
    perm_enabled = "true" if truthy(ctx.setting("security_fail2ban_oris_perm_enabled", "1")) else "false"
    recidive_enabled = "true" if truthy(ctx.setting("security_fail2ban_recidive_enabled", "1")) else "false"
    recidive_maxretry = int_setting(ctx, "security_fail2ban_recidive_maxretry", 5, 1, 1000)
    recidive_findtime = f2b_time_value(ctx.setting("security_fail2ban_recidive_findtime", "7d"), "7d")
    recidive_bantime = f2b_time_value(ctx.setting("security_fail2ban_recidive_bantime", "-1"), "-1")
    perm_bantime = f2b_time_value(ctx.setting("security_fail2ban_perm_bantime", "-1"), "-1")
    atomic_write("/etc/fail2ban/jail.d/oris-security.conf", f'''# ORIS Security Center - generated
[sshd]
enabled = true
backend = systemd
port = ssh
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}

[oris-nginx-phpmyadmin]
enabled = {pma_enabled}
filter = oris-nginx-phpmyadmin
logpath = /var/log/nginx/access.log
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}

[oris-nginx-badbots]
enabled = {bots_enabled}
filter = oris-nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}

[oris-perm]
enabled = {perm_enabled}
filter = oris-perm
logpath = /var/log/oris-security.log
backend = polling
bantime = {perm_bantime}
findtime = 600
maxretry = 1
action = iptables-allports[name=oris-perm]

[recidive]
enabled = {recidive_enabled}
filter = recidive
logpath = /var/log/fail2ban.log
backend = polling
banaction = iptables-allports
bantime = {recidive_bantime}
findtime = {recidive_findtime}
maxretry = {recidive_maxretry}
''')


def valid_port(p: str) -> bool:
    if ":" in p:
        a, b = p.split(":", 1)
        return a.isdigit() and b.isdigit() and 1 <= int(a) <= int(b) <= 65535
    return p.isdigit() and 1 <= int(p) <= 65535

def normalize_port(p: str) -> str:
    return str(p or "").strip().replace("-", ":")


def parse_port_token(token: str) -> tuple[str, str, str] | None:
    """
    Podporuje:
      tcp:21:public
      tcp:40000-40100:public
      tcp:40000:40100:public
    Vrací: proto, port_pro_ufw, scope
    """
    raw = str(token or "").strip()
    parts = raw.split(":")

    if len(parts) == 3:
        proto, port, scope = parts
    elif len(parts) == 4:
        proto = parts[0]
        port = parts[1] + ":" + parts[2]
        scope = parts[3]
    else:
        return None

    proto = proto.lower().strip()
    port = normalize_port(port)
    scope = scope.lower().strip()

    if proto not in {"tcp", "udp"}:
        return None

    if scope not in {"public", "lan", "localhost"}:
        return None

    if not valid_port(port):
        return None

    return proto, port, scope

def valid_ip_or_cidr(value: str) -> bool:
    if not value:
        return True
    try:
        if "/" in value:
            ipaddress.ip_network(value, strict=False)
        else:
            ipaddress.ip_address(value)
        return True
    except Exception:
        return False


def payload_dict(job: dict) -> dict:
    p = job.get("payload")
    if not p:
        return {}
    if isinstance(p, dict):
        return p
    try:
        return json.loads(p)
    except Exception:
        return {}


def _is_ipv6(ip: str) -> bool:
    try:
        obj = ipaddress.ip_network(ip, strict=False) if "/" in ip else ipaddress.ip_address(ip)
        return obj.version == 6
    except Exception:
        return False


def _iptables_bin(ip: str) -> str:
    return "ip6tables" if _is_ipv6(ip) else "iptables"


def firewall_block(ip: str) -> str:
    if not valid_ip_or_cidr(ip) or not ip:
        raise RuntimeError("Neplatná IP/CIDR.")
    bin = _iptables_bin(ip)
    chain = "ORISBLOCK"
    run([bin, "-N", chain], check=False)
    rc, _ = run([bin, "-C", chain, "-s", ip, "-j", "DROP"], check=False)
    if rc != 0:
        run([bin, "-A", chain, "-s", ip, "-j", "DROP"])
    rc, _ = run([bin, "-C", "INPUT", "-j", chain], check=False)
    if rc != 0:
        run([bin, "-I", "INPUT", "-j", chain])
    return f"{bin}: {ip} přidáno do ORISBLOCK"


def firewall_unblock(ip: str) -> str:
    if not valid_ip_or_cidr(ip) or not ip:
        raise RuntimeError("Neplatná IP/CIDR.")
    bin = _iptables_bin(ip)
    run([bin, "-D", "ORISBLOCK", "-s", ip, "-j", "DROP"], check=False)
    return f"{bin}: {ip} odebráno z ORISBLOCK"


def _valid_jail(name: str) -> bool:
    return bool(re.match(r"^[A-Za-z0-9_.:-]+$", name or ""))


def _build_panel_f2b(payload: dict) -> str:
    maxretry = max(1, int(payload.get("maxretry") or 5))
    findtime = max(1, int(payload.get("findtime") or 600))
    bantime = max(1, int(payload.get("bantime") or 3600))
    recidive_maxretry = max(1, int(payload.get("recidive_maxretry") or 5))
    recidive_findtime = f2b_time_value(payload.get("recidive_findtime", "7d"), "7d")
    recidive_bantime = f2b_time_value(payload.get("recidive_bantime", "-1"), "-1")
    perm_bantime = f2b_time_value(payload.get("perm_bantime", "-1"), "-1")
    j = payload.get("jails") or {}
    def en(name: str, default: bool = False) -> str:
        return "true" if truthy(j.get(name, "1" if default else "0")) else "false"
    return f'''# AUTOGENERATED by ORIS Security Center. Do not edit manually.
[DEFAULT]
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}

[sshd]
enabled = {en("sshd", True)}
backend = systemd
port = ssh

[oris-nginx-phpmyadmin]
enabled = {en("oris-nginx-phpmyadmin", True)}
filter = oris-nginx-phpmyadmin
logpath = /var/log/nginx/access.log

[oris-nginx-badbots]
enabled = {en("oris-nginx-badbots", True)}
filter = oris-nginx-badbots
logpath = /var/log/nginx/access.log

[postfix]
enabled = {en("postfix", False)}

[postfix-sasl]
enabled = {en("postfix-sasl", False)}

[dovecot]
enabled = {en("dovecot", False)}

[recidive]
enabled = {en("recidive", True)}
filter = recidive
logpath = /var/log/fail2ban.log
backend = polling
banaction = iptables-allports
bantime = {recidive_bantime}
findtime = {recidive_findtime}
maxretry = {recidive_maxretry}

[oris-perm]
enabled = {en("oris-perm", True)}
filter = oris-perm
logpath = /var/log/oris-security.log
backend = polling
bantime = {perm_bantime}
findtime = 600
maxretry = 1
action = iptables-allports[name=oris-perm]
'''


def _run_ufw_rule(payload: dict) -> tuple[int, str]:
    action = str(payload.get("action", "allow")).lower().strip()
    direction = str(payload.get("dir", "in")).lower().strip()
    port = str(payload.get("port", "")).strip()
    proto = str(payload.get("proto", "tcp")).lower().strip()
    source = str(payload.get("from", payload.get("source", ""))).strip()
    toip = str(payload.get("toip", "")).strip()
    comment = str(payload.get("comment", "")).strip()[:60]
    if action not in {"allow", "deny", "reject", "limit"}:
        raise RuntimeError("Neplatná UFW akce.")
    if direction not in {"in", "out"}:
        raise RuntimeError("Neplatný směr UFW pravidla.")
    if proto not in {"tcp", "udp", "any"}:
        raise RuntimeError("Neplatný protokol.")
    if not valid_port(port):
        raise RuntimeError("Neplatný port.")
    if source and not valid_ip_or_cidr(source):
        raise RuntimeError("Neplatná FROM IP/CIDR.")
    if toip and not valid_ip_or_cidr(toip):
        raise RuntimeError("Neplatná TO IP/CIDR.")
    cmd = ["ufw"]
    if direction == "out":
        cmd += [action, "out"]
        if toip:
            cmd += ["to", toip, "port", port]
            if proto != "any":
                cmd += ["proto", proto]
        else:
            cmd += [port if proto == "any" else f"{port}/{proto}"]
    else:
        cmd += [action]
        if source:
            cmd += ["from", source, "to", "any", "port", port]
            if proto != "any":
                cmd += ["proto", proto]
        else:
            cmd += [port if proto == "any" else f"{port}/{proto}"]
    if comment:
        cmd += ["comment", comment]
    return run(cmd, check=False)


def handle(ctx: Ctx, job: dict) -> None:
    job_id = int(job["id"])
    typ = str(job["type"])
    payload = payload_dict(job)

    if typ == "security_apply":
        ensure_security_files(ctx)
        write_phpmyadmin_snippet(ctx)
        write_fail2ban_config(ctx)
        run(["systemctl", "restart", "fail2ban"], check=False)
        from .panel import write_panel_vhost
        write_panel_vhost(ctx)
        ctx.nginx_reload_checked()
        ctx.job_log(job_id, "Security Center konfigurace aplikována: Nginx limity, phpMyAdmin ochrana, admin allowlist, Fail2ban.")
        return

    if typ == "firewall_block_ip":
        ctx.job_log(job_id, firewall_block(str(payload.get("ip", "")).strip()))
        return
    if typ == "firewall_unblock_ip":
        ctx.job_log(job_id, firewall_unblock(str(payload.get("ip", "")).strip()))
        return
    if typ == "fail2ban_apply_panel_config":
        write_fail2ban_filters()
        j = payload.get("jails") or {}
        ctx.set_setting("security_fail2ban_maxretry", str(payload.get("maxretry", 5)))
        ctx.set_setting("security_fail2ban_findtime", str(payload.get("findtime", 600)))
        ctx.set_setting("security_fail2ban_bantime", str(payload.get("bantime", 3600)))
        ctx.set_setting("security_fail2ban_phpmyadmin_enabled", "1" if truthy(j.get("oris-nginx-phpmyadmin", "1")) else "0")
        ctx.set_setting("security_fail2ban_badbots_enabled", "1" if truthy(j.get("oris-nginx-badbots", "1")) else "0")
        ctx.set_setting("security_fail2ban_recidive_enabled", "1" if truthy(j.get("recidive", "1")) else "0")
        ctx.set_setting("security_fail2ban_oris_perm_enabled", "1" if truthy(j.get("oris-perm", "1")) else "0")
        ctx.set_setting("security_fail2ban_recidive_maxretry", str(payload.get("recidive_maxretry", 5)))
        ctx.set_setting("security_fail2ban_recidive_findtime", f2b_time_value(payload.get("recidive_findtime", "7d"), "7d"))
        ctx.set_setting("security_fail2ban_recidive_bantime", f2b_time_value(payload.get("recidive_bantime", "-1"), "-1"))
        ctx.set_setting("security_fail2ban_perm_bantime", f2b_time_value(payload.get("perm_bantime", "-1"), "-1"))
        atomic_write("/etc/fail2ban/jail.d/oris-panel.conf", _build_panel_f2b(payload))
        rc, out = run(["systemctl", "restart", "fail2ban"], check=False)
        ctx.job_log(job_id, out.strip() or f"fail2ban restart exit={rc}")
        if rc != 0:
            raise RuntimeError(out)
        return
    if typ == "ufw_enable":
        rc, out = run(["ufw", "--force", "enable"], check=False)
        ctx.job_log(job_id, out.strip() or f"ufw enable exit={rc}")
        if rc != 0: raise RuntimeError(out)
        return
    if typ == "ufw_disable":
        rc, out = run(["ufw", "disable"], check=False)
        ctx.job_log(job_id, out.strip() or f"ufw disable exit={rc}")
        if rc != 0: raise RuntimeError(out)
        return
    if typ == "ufw_reload":
        rc, out = run(["ufw", "reload"], check=False)
        ctx.job_log(job_id, out.strip() or f"ufw reload exit={rc}")
        if rc != 0: raise RuntimeError(out)
        return
    if typ == "ufw_default":
        incoming = str(payload.get("in", payload.get("def_in", "deny"))).lower().strip()
        outgoing = str(payload.get("out", payload.get("def_out", "allow"))).lower().strip()
        if incoming not in {"allow", "deny", "reject"} or outgoing not in {"allow", "deny", "reject"}:
            raise RuntimeError("Neplatná default politika.")
        rc1, out1 = run(["ufw", "default", incoming, "incoming"], check=False)
        rc2, out2 = run(["ufw", "default", outgoing, "outgoing"], check=False)
        ctx.job_log(job_id, (out1 + out2).strip() or "Default politika nastavena.")
        if rc1 != 0 or rc2 != 0: raise RuntimeError((out1 + out2).strip())
        return
    if typ == "ufw_allow":
        rc, out = _run_ufw_rule({"action": "allow", "dir": "in", "port": payload.get("port", ""), "proto": payload.get("proto", "tcp"), "from": payload.get("source", "")})
        ctx.job_log(job_id, out.strip() or "UFW pravidlo přidáno.")
        if rc != 0: raise RuntimeError(out)
        return
    if typ == "ufw_rule":
        rc, out = _run_ufw_rule(payload)
        ctx.job_log(job_id, out.strip() or "UFW pravidlo přidáno.")
        if rc != 0: raise RuntimeError(out)
        return
    if typ == "ufw_apply_ports":
        selected = payload.get("ports") or []

        if not isinstance(selected, list) or not selected:
            raise RuntimeError("Nic nebylo vybráno.")

        lan_net = str(payload.get("lan_net", "192.168.0.0/16")).strip()
        scope = str(payload.get("scope", "auto")).strip().lower()

        if scope not in {"auto", "public", "lan"}:
            scope = "auto"

        if lan_net and not valid_ip_or_cidr(lan_net):
            raise RuntimeError(f"Neplatný LAN rozsah: {lan_net}")

        any_err = False
        added = 0
        skipped = 0

        for token in selected:
            parsed = parse_port_token(str(token))

            if not parsed:
                skipped += 1
                ctx.job_log(job_id, f"SKIP neplatný token portu: {token}")
                continue

            proto, port, klass = parsed

            if klass == "localhost":
                skipped += 1
                ctx.job_log(job_id, f"SKIP localhost port {proto}/{port}")
                continue

            final_scope = scope if scope in {"public", "lan"} else ("lan" if klass == "lan" else "public")

            rule_payload = {
                "action": "allow",
                "dir": "in",
                "port": port,
                "proto": proto,
                "comment": f"ORIS auto {klass} {proto}/{port}",
            }

            if final_scope == "lan":
                rule_payload["from"] = lan_net

            rc, out = _run_ufw_rule(rule_payload)

            ctx.job_log(
                job_id,
                f"{proto}/{port} {final_scope}: " + (out.strip() or f"exit={rc}")
            )

            if rc != 0:
                any_err = True
            else:
                added += 1

        run(["ufw", "reload"], check=False)

        ctx.job_log(job_id, f"UFW auto porty hotovo. Přidáno: {added}, přeskočeno: {skipped}")

        if any_err:
            raise RuntimeError("Některá UFW pravidla se nepodařilo přidat. Viz log jobu.")

        return
    if typ == "ufw_delete":
        num = str(payload.get("num", "")).strip()
        if not num.isdigit() or int(num) < 1: raise RuntimeError("Neplatné číslo UFW pravidla.")
        rc, out = run(["ufw", "--force", "delete", num], check=False)
        ctx.job_log(job_id, out.strip() or "UFW pravidlo smazáno.")
        if rc != 0: raise RuntimeError(out)
        return
    if typ == "fail2ban_reload":
        rc, out = run(["systemctl", "restart", "fail2ban"], check=False)
        ctx.job_log(job_id, out.strip() or f"fail2ban restart exit={rc}")
        if rc != 0: raise RuntimeError(out)
        return
    if typ in {"fail2ban_ban_ip", "fail2ban_unban_ip"}:
        jail = str(payload.get("jail", "sshd")).strip()
        ip = str(payload.get("ip", "")).strip()
        if not _valid_jail(jail): raise RuntimeError("Neplatný jail.")
        if not valid_ip_or_cidr(ip) or "/" in ip: raise RuntimeError("Neplatná IP adresa.")
        action = "banip" if typ == "fail2ban_ban_ip" else "unbanip"
        rc, out = run(["fail2ban-client", "set", jail, action, ip], check=False)
        ctx.job_log(job_id, out.strip() or f"{action} {ip} in {jail}")
        if rc != 0: raise RuntimeError(out)
        return
    raise RuntimeError(f"Plugin security neumí job {typ}")
