<?php
require __DIR__.'/_boot.php';
require __DIR__.'/_view.php';
require_admin();

render($pdo, t('page.network_stat.title', [], 'Síťový monitoring'), function() { ?>
  <div class="card">
    <h2><?=h(t('page.network_stat.title', [], 'Síťový monitoring'))?></h2>
  </div>

  <div class="card">
    <h3><?=h(t('network.heading', [], 'Network'))?></h3>
    <small id="netSummary"><?=h(t('common.loading', [], 'Načítám…'))?></small>

    <div class="row" style="gap:10px; margin-top:10px; flex-wrap:wrap">
      <span class="pill" id="pub4" style="display:none"><?=h(t('network.public_ipv4_empty', [], 'Veřejná IPv4: —'))?></span>
      <span class="pill" id="pub6" style="display:none"><?=h(t('network.public_ipv6_empty', [], 'Veřejná IPv6: —'))?></span>
    </div>

    <div style="margin-top:12px">
      <div class="table-scroll">
        <table id="ifaceTable">
          <tr>
            <th><?=h(t('network.col.interface', [], 'Interface'))?></th>
            <th><?=h(t('common.status', [], 'Stav'))?></th>
            <th><?=h(t('network.col.mac', [], 'MAC'))?></th>
            <th><?=h(t('network.col.ipv4', [], 'IPv4'))?></th>
            <th><?=h(t('network.col.ipv6', [], 'IPv6'))?></th>
          </tr>
          <!-- rows generated by JS -->
        </table>
        <small><?=t('network.ifaces.help', [], 'Adresy jsou vypsané přímo z <code>ip addr</code>. Pokud IPv6 na serveru není, sloupec zůstane prázdný.')?></small>
      </div>
    </div>

    <div style="margin-top:12px">
      <canvas id="netCanvas" style="width:100%; height:220px; border:1px solid #e5e5e5; border-radius:10px; background:#fff"></canvas>
    </div>

    <div style="margin-top:12px">
      <div class="table-scroll">
        <table id="netTable">
          <tr>
            <th><?=h(t('network.col.interface', [], 'Interface'))?></th>
            <th><?=h(t('network.col.rx', [], 'Příchozí'))?></th>
            <th><?=h(t('network.col.tx', [], 'Odchozí'))?></th>
            <th><?=h(t('network.col.total', [], 'Celkem'))?></th>
            <th style="width:220px"><?=h(t('network.col.graph_60s', [], 'Graf (poslední ~60s)'))?></th>
          </tr>
          <!-- rows generated by JS -->
        </table>
        <small><?=h(t('network.stats.help', [], 'RX/TX jsou rychlosti (průměr mezi posledními dvěma vzorky). “lo” je typicky lokální loopback.'))?></small>
      </div>
    </div>
  </div>

  <script>
  const I18N = {
    publicIpv4: <?=json_encode(t('network.public_ipv4', [], 'Veřejná IPv4'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    publicIpv6: <?=json_encode(t('network.public_ipv6', [], 'Veřejná IPv6'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    total: <?=json_encode(t('network.summary.total', [], 'Celkem'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    counters: <?=json_encode(t('network.summary.counters', [], 'Counters'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    readError: <?=json_encode(t('network.error.read_data', [], 'Chyba čtení dat…'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>
  };

  // ---- format helpers ----
  function bytes(n) {
    if (n == null || isNaN(n)) return '—';
    const units = ['B','KiB','MiB','GiB','TiB'];
    let i = 0; let x = Number(n);
    while (x >= 1024 && i < units.length-1) { x /= 1024; i++; }
    return (x >= 10 ? x.toFixed(0) : x.toFixed(1)) + ' ' + units[i];
  }

  function fmtBitRate(bytesPerSec) {
    if (bytesPerSec == null || isNaN(bytesPerSec)) return '—';
    let bps = Number(bytesPerSec) * 8;
    const units = ['bit/s','Kbit/s','Mbit/s','Gbit/s'];
    let i = 0;
    while (bps >= 1000 && i < units.length-1) { bps /= 1000; i++; }
    return (bps >= 10 ? bps.toFixed(0) : bps.toFixed(1)) + ' ' + units[i];
  }

  function isIPv6(s){ return typeof s === 'string' && s.includes(':'); }
  function isIPv4(s){ return typeof s === 'string' && /^\d{1,3}(?:\.\d{1,3}){3}$/.test(s); }

  // ---- network state ----
  const netState = {
    lastTs: null,
    lastIf: null, // iface -> {rx,tx}
    seriesTotalRx: [],
    seriesTotalTx: [],
    maxPointsMain: 180, // 3 min @1s
    perIfSeries: new Map(), // iface -> {rx:[], tx:[], max:60}
    rows: new Map(), // iface -> {tr, rxEl, txEl, totEl, canvas, ctx}
    ifaceRows: new Map(), // iface -> tr
  };

  function ensureIfaceRow(iface){
    const t = document.getElementById('ifaceTable');
    if (netState.ifaceRows.has(iface)) return netState.ifaceRows.get(iface);

    const tr = document.createElement('tr');
    const tdIf = document.createElement('td'); tdIf.textContent = iface; tdIf.style.fontFamily='monospace';
    const tdSt = document.createElement('td');
    const tdMac = document.createElement('td'); tdMac.style.fontFamily='monospace';
    const td4 = document.createElement('td'); td4.style.fontFamily='monospace';
    const td6 = document.createElement('td'); td6.style.fontFamily='monospace';

    tr.appendChild(tdIf);
    tr.appendChild(tdSt);
    tr.appendChild(tdMac);
    tr.appendChild(td4);
    tr.appendChild(td6);
    t.appendChild(tr);

    const row = {tr, tdSt, tdMac, td4, td6};
    netState.ifaceRows.set(iface, row);
    return row;
  }

  function ensureRow(iface) {
    const table = document.getElementById('netTable');
    if (netState.rows.has(iface)) return netState.rows.get(iface);

    const tr = document.createElement('tr');

    const tdIf = document.createElement('td');
    tdIf.textContent = iface;
    tdIf.style.fontFamily = 'monospace';

    const tdRx = document.createElement('td');
    const tdTx = document.createElement('td');
    const tdTot = document.createElement('td');

    const tdG = document.createElement('td');
    const cv = document.createElement('canvas');
    cv.width = 200;
    cv.height = 46;
    cv.style.width = '200px';
    cv.style.height = '46px';
    cv.style.border = '1px solid #eee';
    cv.style.borderRadius = '8px';
    cv.style.background = '#fff';
    tdG.appendChild(cv);

    tr.appendChild(tdIf);
    tr.appendChild(tdRx);
    tr.appendChild(tdTx);
    tr.appendChild(tdTot);
    tr.appendChild(tdG);

    table.appendChild(tr);

    const row = { tr, rxEl: tdRx, txEl: tdTx, totEl: tdTot, canvas: cv, ctx: cv.getContext('2d') };
    netState.rows.set(iface, row);
    return row;
  }

  function pushSeries(arr, v, max) {
    arr.push(v);
    if (arr.length > max) arr.splice(0, arr.length - max);
  }

  function drawSeries(ctx, w, h, seriesA, seriesB) {
    ctx.clearRect(0,0,w,h);

    const maxV = Math.max(1,
      ...seriesA.map(x=>x||0),
      ...seriesB.map(x=>x||0)
    );

    function y(v){ return h - (v/maxV)*(h-10) - 5; }

    // grid
    ctx.strokeStyle = '#eee';
    ctx.lineWidth = 1;
    for (let i=1;i<=3;i++) {
      const yy = (h/4)*i;
      ctx.beginPath(); ctx.moveTo(0,yy); ctx.lineTo(w,yy); ctx.stroke();
    }

    // RX
    ctx.strokeStyle = '#2563eb';
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let i=0;i<seriesA.length;i++) {
      const x = (i/(Math.max(1,seriesA.length-1)))*(w-10)+5;
      const yy = y(seriesA[i]||0);
      if (i===0) ctx.moveTo(x,yy); else ctx.lineTo(x,yy);
    }
    ctx.stroke();

    // TX
    ctx.strokeStyle = '#16a34a';
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let i=0;i<seriesB.length;i++) {
      const x = (i/(Math.max(1,seriesB.length-1)))*(w-10)+5;
      const yy = y(seriesB[i]||0);
      if (i===0) ctx.moveTo(x,yy); else ctx.lineTo(x,yy);
    }
    ctx.stroke();

    ctx.fillStyle = '#666';
    ctx.font = '12px sans-serif';
    ctx.fillText(fmtBitRate(maxV), 10, h-12);
  }

  function drawPerIface(ctx, w, h, rxSeries, txSeries) {
    ctx.clearRect(0,0,w,h);
    const maxV = Math.max(1,
      ...rxSeries.map(x=>x||0),
      ...txSeries.map(x=>x||0)
    );
    function y(v){ return h - (v/maxV)*(h-8) - 4; }

    ctx.strokeStyle = '#eee';
    ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(0,h-1); ctx.lineTo(w,h-1); ctx.stroke();

    ctx.strokeStyle = '#2563eb';
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let i=0;i<rxSeries.length;i++) {
      const x = (i/(Math.max(1,rxSeries.length-1)))*(w-8)+4;
      const yy = y(rxSeries[i]||0);
      if (i===0) ctx.moveTo(x,yy); else ctx.lineTo(x,yy);
    }
    ctx.stroke();

    ctx.strokeStyle = '#16a34a';
    ctx.lineWidth = 2;
    ctx.beginPath();
    for (let i=0;i<txSeries.length;i++) {
      const x = (i/(Math.max(1,txSeries.length-1)))*(w-8)+4;
      const yy = y(txSeries[i]||0);
      if (i===0) ctx.moveTo(x,yy); else ctx.lineTo(x,yy);
    }
    ctx.stroke();
  }

  function renderPublicIPs(pub) {
    const e4 = document.getElementById('pub4');
    const e6 = document.getElementById('pub6');

    const v4 = pub && isIPv4(pub.ipv4) ? pub.ipv4 : null;
    const v6 = pub && isIPv6(pub.ipv6) ? pub.ipv6 : null;

    if (v4) {
      e4.textContent = I18N.publicIpv4 + ': ' + v4;
      e4.style.display = '';
    } else {
      e4.style.display = 'none';
    }

    // Tvoje přání: když není IPv6, nevypisovat nic.
    if (v6) {
      e6.textContent = I18N.publicIpv6 + ': ' + v6;
      e6.style.display = '';
    } else {
      e6.style.display = 'none';
    }
  }

  function renderIfaces(list) {
    if (!Array.isArray(list)) return;
    for (const it of list) {
      const name = it.ifname;
      if (!name) continue;
      const row = ensureIfaceRow(name);

      const st = (it.operstate || it.state || '—');
      row.tdSt.textContent = st;
      row.tdMac.textContent = it.mac || '—';

      const v4 = Array.isArray(it.ipv4) ? it.ipv4.map(a => a.ip + (a.prefixlen!=null?'/'+a.prefixlen:'')) : [];
      const v6 = Array.isArray(it.ipv6) ? it.ipv6.map(a => a.ip + (a.prefixlen!=null?'/'+a.prefixlen:'')) : [];

      row.td4.textContent = v4.length ? v4.join('  ') : '—';
      row.td6.textContent = v6.length ? v6.join('  ') : '—';
    }
  }

  // ---- main tick ----
  async function tick() {
    try {
      const r = await fetch('/api/system_stats.php', { cache: 'no-store' });
      const j = await r.json();
      if (!j || !j.ok) throw new Error('bad response');

      const net = j.net || {};
      renderPublicIPs(net.public || null);
      renderIfaces(net.interfaces || []);

      const ifaces = net.ifaces || {};
      const ts = j.ts || Math.floor(Date.now()/1000);

      // compute dt
      let dt = 1;
      if (netState.lastTs != null) dt = Math.max(1, ts - netState.lastTs);

      // totals from counters
      let sumRx = 0, sumTx = 0;
      for (const k in ifaces) {
        sumRx += (ifaces[k].rx_bytes || 0);
        sumTx += (ifaces[k].tx_bytes || 0);
      }

      // rates
      let totalRxRate = 0, totalTxRate = 0;

      if (netState.lastIf) {
        for (const iface in ifaces) {
          const cur = ifaces[iface];
          const prev = netState.lastIf[iface];
          const rx = cur.rx_bytes || 0;
          const tx = cur.tx_bytes || 0;

          let rxRate = null, txRate = null;

          if (prev) {
            rxRate = Math.max(0, (rx - prev.rx) / dt);
            txRate = Math.max(0, (tx - prev.tx) / dt);
            totalRxRate += rxRate;
            totalTxRate += txRate;
          }

          // per iface series + row
          const row = ensureRow(iface);
          row.rxEl.textContent = rxRate == null ? '—' : fmtBitRate(rxRate);
          row.txEl.textContent = txRate == null ? '—' : fmtBitRate(txRate);
          row.totEl.textContent = (rxRate == null || txRate == null) ? '—' : fmtBitRate(rxRate + txRate);

          if (!netState.perIfSeries.has(iface)) netState.perIfSeries.set(iface, {rx:[], tx:[], max:60});
          const s = netState.perIfSeries.get(iface);
          pushSeries(s.rx, rxRate || 0, s.max);
          pushSeries(s.tx, txRate || 0, s.max);
          drawPerIface(row.ctx, row.canvas.width, row.canvas.height, s.rx, s.tx);
        }
      }

      // store prev
      const lastIf = {};
      for (const iface in ifaces) {
        lastIf[iface] = { rx: (ifaces[iface].rx_bytes||0), tx: (ifaces[iface].tx_bytes||0) };
      }
      netState.lastIf = lastIf;
      netState.lastTs = ts;

      // main series
      pushSeries(netState.seriesTotalRx, totalRxRate || 0, netState.maxPointsMain);
      pushSeries(netState.seriesTotalTx, totalTxRate || 0, netState.maxPointsMain);

      // draw main
      const cv = document.getElementById('netCanvas');
      const ctx = cv.getContext('2d');
      // make canvas resolution match CSS width for crisp lines
      const rect = cv.getBoundingClientRect();
      cv.width = Math.max(300, Math.floor(rect.width * (window.devicePixelRatio || 1)));
      cv.height = Math.floor(220 * (window.devicePixelRatio || 1));
      ctx.scale((window.devicePixelRatio || 1), (window.devicePixelRatio || 1));
      drawSeries(ctx, rect.width, 220, netState.seriesTotalRx, netState.seriesTotalTx);

      // summary
      document.getElementById('netSummary').textContent =
        `${I18N.total} RX ${fmtBitRate(totalRxRate)} / TX ${fmtBitRate(totalTxRate)} • ${I18N.counters}: RX ${bytes(sumRx)} / TX ${bytes(sumTx)}`;

    } catch (e) {
      document.getElementById('netSummary').textContent = I18N.readError;
    }
  }

let busy = false;

async function tickLoop() {
  if (busy) return;
  busy = true;

  try {
    await tick();
  } finally {
    busy = false;
    setTimeout(tickLoop, 2000);
  }
}

tickLoop();
  </script>

<?php }); ?>
