<?php
require __DIR__.'/_boot.php';
require __DIR__.'/_view.php';
require_admin();

render($pdo, t('page.stoarge-cpu.title', [], 'Systém'), function() { ?>
  <div class="card">
    <h2><?=h(t('storage_cpu.heading', [], 'Systémový monitoring'))?></h2>
  </div>

  <style>
    /* local-only: keep original look, but make bars animate even if global CSS disables transitions */
    .statgrid{display:grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap:12px;}
    .statbox h3{margin:0 0 8px;}
    .bar-track{height:10px;background:#e5e7eb;border-radius:999px;overflow:hidden;margin-top:10px}
    .bar-fill{height:10px;width:0%;background:#3b82f6;}
  </style>

  <div class="card">
    <div id="statGrid" class="statgrid">
      <!-- boxes generated by JS -->
    </div>
  </div>

  <div class="card">
    <h3><?=h(t('storage_cpu.storage.heading', [], 'Detekovaná úložiště'))?></h3>
    <small><?=h(t('storage_cpu.storage.help_prefix', [], 'Výpis z'))?> <code>lsblk</code> <?=h(t('storage_cpu.storage.help_suffix', [], '(disky/oddíly, FS, mountpoint, model). Pokud tu něco chybí, nejspíš nemáš práva nebo lsblk není k dispozici.'))?></small>

    <div style="margin-top:12px" class="table-scroll">
      <table id="storageTable">
        <tr>
          <th><?=h(t('storage_cpu.col.device', [], 'Zařízení'))?></th>
          <th><?=h(t('storage_cpu.col.type', [], 'Typ'))?></th>
          <th><?=h(t('storage_cpu.col.size', [], 'Velikost'))?></th>
          <th><?=h(t('storage_cpu.col.fs', [], 'FS'))?></th>
          <th><?=h(t('storage_cpu.col.mount', [], 'Mount'))?></th>
          <th><?=h(t('storage_cpu.col.model', [], 'Model'))?></th>
          <th><?=h(t('storage_cpu.col.transport', [], 'Transport'))?></th>
        </tr>
        <!-- rows generated by JS -->
      </table>
    </div>
  </div>

  <script>
  const I18N = {
    noData: <?=json_encode(t('storage_cpu.js.no_data', [], 'Žádná data.'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    loading: <?=json_encode(t('common.loading', [], 'Načítám…'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    usedPct: <?=json_encode(t('storage_cpu.js.used_pct', [], ' % použito'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    disk: <?=json_encode(t('storage_cpu.js.disk', [], 'Disk'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    used: <?=json_encode(t('storage_cpu.js.used', [], 'Použito'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    total: <?=json_encode(t('storage_cpu.js.total', [], 'Celkem'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    free: <?=json_encode(t('storage_cpu.js.free', [], 'Volné'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    avail: <?=json_encode(t('storage_cpu.js.available', [], 'Dostupné'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    load: <?=json_encode(t('storage_cpu.js.load', [], 'Zátěž'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    badResponse: <?=json_encode(t('storage_cpu.js.bad_response', [], 'Špatná odpověď API'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    ram: <?=json_encode(t('storage_cpu.js.ram', [], 'RAM'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>,
    cpu: <?=json_encode(t('storage_cpu.js.cpu', [], 'CPU'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)?>
  };
  // ---- format helpers ----
  function bytes(n) {
    if (n == null || isNaN(n)) return '—';
    const units = ['B','KiB','MiB','GiB','TiB'];
    let i = 0; let x = Number(n);
    while (x >= 1024 && i < units.length-1) { x /= 1024; i++; }
    return (x >= 10 ? x.toFixed(0) : x.toFixed(1)) + ' ' + units[i];
  }

  function clampPct(x) {
    if (x == null || isNaN(x)) return 0;
    x = Number(x);
    if (x < 0) return 0;
    if (x > 100) return 100;
    return x;
  }

function setBar(el, pct) {
  pct = clampPct(pct);
  el.style.setProperty('transition', 'width .7s ease', 'important');
  el.style.setProperty('will-change', 'width', 'important');

  // NEZAČÍNEJ od 0 – nech první nastavení rovnou na target
  if (!el.dataset.inited) {
    el.dataset.inited = '1';
    el.style.width = pct.toFixed(1) + '%';
    return;
  }

  requestAnimationFrame(() => { el.style.width = pct.toFixed(1) + '%'; });
}

  function esc(s) {
    return String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  }

  function flattenLsblk(devs, depth=0, out=[]) {
    for (const d of (devs || [])) {
      out.push({
        name: d.name ?? '',
        kname: d.kname ?? '',
        type: d.type ?? '',
        size: d.size ?? null,
        fstype: d.fstype ?? '',
        mountpoint: d.mountpoint ?? '',
        model: d.model ?? '',
        tran: d.tran ?? '',
        rota: d.rota ?? null,
        depth,
      });
      if (d.children) flattenLsblk(d.children, depth+1, out);
    }
    return out;
  }

  function renderStorage(devs) {
    const table = document.getElementById('storageTable');
    while (table.rows.length > 1) table.deleteRow(1);
    const flat = flattenLsblk(devs);
    if (!flat.length) {
      const tr = table.insertRow();
      const td = tr.insertCell();
      td.colSpan = 7;
      td.textContent = I18N.noData;
      return;
    }
    for (const d of flat) {
      const tr = table.insertRow();
      const pad = '\xa0'.repeat(d.depth * 4);
      tr.insertCell().innerHTML = `<span style="font-family:monospace">${pad}${esc(d.name)}</span>`;
      tr.insertCell().textContent = d.type || '—';
      tr.insertCell().textContent = d.size == null ? '—' : bytes(d.size);
      tr.insertCell().textContent = d.fstype || '—';
      tr.insertCell().textContent = d.mountpoint || '—';
      tr.insertCell().textContent = (d.model || '').trim() || '—';
      tr.insertCell().textContent = d.tran || (d.rota === 0 ? 'nvme/ssd' : (d.rota === 1 ? 'hdd' : '—'));
    }
  }

  function normalizeMounts(j) {
    const mounts = (j && j.disk && Array.isArray(j.disk.mounts)) ? j.disk.mounts : null;
    if (mounts && mounts.length) return mounts;

    const out = [];
    if (j && j.disk && j.disk.root) out.push({ mountpoint: '/', ...j.disk.root });
    if (j && j.disk && j.disk.data) out.push({ mountpoint: '/data', ...j.disk.data });
    return out;
  }

  function box(title) {
    const b = document.createElement('div');
    b.className = 'statbox';
    b.innerHTML = `
      <h3>${esc(title)}</h3>
      <div class="pill">${esc(I18N.loading)}</div>
      <div class="bar-track"><div class="bar-fill"></div></div>
      <small></small>
    `;
    return b;
  }

  function fillBox(b, title, pct, subText) {
    b.querySelector('h3').textContent = title;
    const pill = b.querySelector('.pill');
    const small = b.querySelector('small');
    const fill = b.querySelector('.bar-fill');
    pill.textContent = (pct == null ? '—' : Number(pct).toFixed(1) + I18N.usedPct);
    small.textContent = subText || '';
    setBar(fill, pct);
  }

  function renderStats(j) {
    const grid = document.getElementById('statGrid');
    grid.innerHTML = '';

    // disks (mounts)
    const mounts = normalizeMounts(j);
    for (const m of mounts) {
      const b = box(I18N.disk);
      grid.appendChild(b);
      const mp = m.mountpoint || '—';
      fillBox(
        b,
        `${I18N.disk} (${mp})`,
        m.used_pct,
        `${I18N.used} ${bytes(m.used)} / ${I18N.total} ${bytes(m.total)} (${I18N.free} ${bytes(m.free)})`
      );
    }

    // RAM
    const m = j.mem || {};
    const bMem = box(I18N.ram);
    grid.appendChild(bMem);
    fillBox(
      bMem,
      I18N.ram,
      m.used_pct,
      `${I18N.used} ${bytes(m.used)} / ${I18N.total} ${bytes(m.total)} (${I18N.avail} ${bytes(m.available)})`
    );

    // CPU
    const c = j.cpu || {};
    const bCpu = box(I18N.cpu);
    grid.appendChild(bCpu);
    fillBox(
      bCpu,
      I18N.cpu,
      c.usage_pct,
      `${I18N.load}: ${c.load1 ?? '—'} / ${c.load5 ?? '—'} / ${c.load15 ?? '—'}`
    );
    // CPU pill wants just percent
    const pill = bCpu.querySelector('.pill');
    pill.textContent = (c.usage_pct == null ? '—' : c.usage_pct.toFixed(1) + '%');
  }

  async function tick() {
    const r = await fetch('/api/system_stats.php', { cache: 'no-store' });
    const j = await r.json();
    if (!j || !j.ok) throw new Error(I18N.badResponse);

    renderStats(j);

    const devs = (j.storage && (j.storage.devices || j.storage.blockdevices))
      ? (j.storage.devices || j.storage.blockdevices)
      : [];
    renderStorage(devs);
  }

  let busy = false;
  async function tickLoop() {
    if (busy) return;
    busy = true;
    try { await tick(); }
    catch(e){ /* ignore */ }
    finally { busy = false; setTimeout(tickLoop, 3000); }
  }
  tickLoop();
  </script>
<?php }); ?>
